//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundByte.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundByte.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem parsing the response. This could be due to an API change. Please report the following:.
        /// </summary>
        internal static string HttpService_JsonError_Description {
            get {
                return ResourceManager.GetString("HttpService_JsonError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Parsing Error.
        /// </summary>
        internal static string HttpService_JsonError_Title {
            get {
                return ResourceManager.GetString("HttpService_JsonError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track does not have any comments..
        /// </summary>
        internal static string Sources_All_Comments_NoComments_Description {
            get {
                return ResourceManager.GetString("Sources_All_Comments_NoComments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comments..
        /// </summary>
        internal static string Sources_All_Comments_NoComments_Title {
            get {
                return ResourceManager.GetString("Sources_All_Comments_NoComments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string Sources_All_NoResults_Title {
            get {
                return ResourceManager.GetString("Sources_All_NoResults_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is not currently supported for the following service type: {0}..
        /// </summary>
        internal static string Sources_All_NotImplemented_Description {
            get {
                return ResourceManager.GetString("Sources_All_NotImplemented_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not currently supported..
        /// </summary>
        internal static string Sources_All_NotImplemented_Title {
            get {
                return ResourceManager.GetString("Sources_All_NotImplemented_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not tracks in this playlist..
        /// </summary>
        internal static string Sources_All_PlaylistEmpty_Description {
            get {
                return ResourceManager.GetString("Sources_All_PlaylistEmpty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tracks..
        /// </summary>
        internal static string Sources_All_PlaylistEmpty_Title {
            get {
                return ResourceManager.GetString("Sources_All_PlaylistEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any results matching &quot;{0}&quot;..
        /// </summary>
        internal static string Sources_All_Search_NotResults_Description {
            get {
                return ResourceManager.GetString("Sources_All_Search_NotResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no popular items on Fanburst..
        /// </summary>
        internal static string Sources_Fanburst_Explore_NoResults_Description {
            get {
                return ResourceManager.GetString("Sources_Fanburst_Explore_NoResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your Fanburst account to view your likes..
        /// </summary>
        internal static string Sources_Fanburst_Like_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_Fanburst_Like_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fanburst likes were found, like some tracks to get started..
        /// </summary>
        internal static string Sources_Fanburst_Like_NoItems_Description {
            get {
                return ResourceManager.GetString("Sources_Fanburst_Like_NoItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fanburst Account Not Connected.
        /// </summary>
        internal static string Sources_Fanburst_NoAccount_Title {
            get {
                return ResourceManager.GetString("Sources_Fanburst_NoAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your Fanburst Account to view playlists..
        /// </summary>
        internal static string Sources_Fanburst_Playlist_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_Fanburst_Playlist_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fanburst playlists were found, create a playlist to get started..
        /// </summary>
        internal static string Sources_Fanburst_Playlist_NoItems_Description {
            get {
                return ResourceManager.GetString("Sources_Fanburst_Playlist_NoItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or create a SoundByte Account to view and save your history..
        /// </summary>
        internal static string Sources_SoundByte_History_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_SoundByte_History_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start listening to some tracks to build up your history..
        /// </summary>
        internal static string Sources_SoundByte_History_NoResults_Description {
            get {
                return ResourceManager.GetString("Sources_SoundByte_History_NoResults_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No History.
        /// </summary>
        internal static string Sources_SoundByte_History_NoResults_Title {
            get {
                return ResourceManager.GetString("Sources_SoundByte_History_NoResults_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or create a SoundByte Account to view your curated likes..
        /// </summary>
        internal static string Sources_SoundByte_Like_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_SoundByte_Like_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundByte Account Not Connected.
        /// </summary>
        internal static string Sources_SoundByte_NoAccount_Title {
            get {
                return ResourceManager.GetString("Sources_SoundByte_NoAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or create a SoundByte Account to view your curated playlists..
        /// </summary>
        internal static string Sources_SoundByte_Playlist_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_SoundByte_Playlist_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or create a SoundByte Account to view your subscribed podcasts..
        /// </summary>
        internal static string Sources_SoundByte_Podcast_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_SoundByte_Podcast_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your YouTube account to view your likes..
        /// </summary>
        internal static string Sources_YouTube_Like_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_YouTube_Like_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No YouTube likes were found, like some videos to get started..
        /// </summary>
        internal static string Sources_YouTube_Like_NoItems_Description {
            get {
                return ResourceManager.GetString("Sources_YouTube_Like_NoItems_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Account Not Connected.
        /// </summary>
        internal static string Sources_YouTube_NoAccount_Title {
            get {
                return ResourceManager.GetString("Sources_YouTube_NoAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your YouTube Account to view playlists..
        /// </summary>
        internal static string Sources_YouTube_Playlist_NoAccount_Description {
            get {
                return ResourceManager.GetString("Sources_YouTube_Playlist_NoAccount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No YouTube playlists were found, create a playlist to get started..
        /// </summary>
        internal static string Sources_YouTube_Playlist_NoItems_Description {
            get {
                return ResourceManager.GetString("Sources_YouTube_Playlist_NoItems_Description", resourceCulture);
            }
        }
    }
}
